dist: bionic
language: node_js
node_js:
  - "10"
  - "12"
  - "14"
cache:
  npm: true
  directories:
    - .cache

install:
 - npm ci --ignore-scripts

script:
  - npm run build
  - npm run test
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: Release
      if: tag IS present
      node_js: "14"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        on:
          tags: true
